apiVersion: v1
kind: ConfigMap
metadata:
  name: api-shopping-cm
  namespace: main
data:
  environment: Production
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-shopping-dpl
  namespace: main
spec:
  selector:
    matchLabels:
      app: api-shopping
  template:
    metadata:
      labels:
        app: api-shopping
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: /metrics-text
        prometheus.io/port: "8080"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: api-shopping
        image: ghcr.io/ivan-shalimov/shopping.server:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-shopping-cm
              key: environment
        - name: ConnectionStrings__Shopping
          valueFrom:
            configMapKeyRef:
              name: api-shopping-cm
              key: connection_strings_shopping
---
apiVersion: v1
kind: Service
metadata:
  name: api-shopping-srv
  namespace: main
spec:
  selector:
    app: api-shopping
  type: LoadBalancer
  ports:
  - port: 9092
    targetPort: 8080