version: '3.4'
name: develop-infrastructure
networks:
  develop-network:
    name: develop-network
services:  
  ms-sql:
    container_name: ms-sql
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
            SA_PASSWORD: Password1!
            ACCEPT_EULA: "Y"
    networks:
      - develop-network
    ports:
      - "1433:1433"
    volumes:
      - ms_sql_volume:/var/opt/mssql
    restart: always
volumes:
  ms_sql_volume:
    external: true