version: '3.4'
name: shopping-infrastructure
networks:
  shopping-network:
    name: shopping-network
services:  
  shopping-ms-sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
            SA_PASSWORD: T3rr$$b!e
            ACCEPT_EULA: "Y"
    networks:
      shopping-network:
        aliases:
          - shopping-ms-sql
    ports:
      - "1434:1433"
    volumes:
      - shopping:/var/opt/mssql
    labels:
      NAME: "shopping-ms-sql"
    restart: always
volumes:
  shopping:
    external: true