version: '3.4'

networks:
  develop-network:
    external: true
services:
  shopping.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Shopping=Server=ms-sql;Database=sh-shopping-dev;User=sa;Password=Password1!;Connection Timeout=30;Encrypt=False;
      - OtplCollectorEndpoint=http://192.168.0.100:4317
    image: shoppingserver
    container_name: shoppingserver
    hostname: shoppingserver
    build:
      context: .
      dockerfile: Shopping/Server/Dockerfile
    networks:
      - develop-network
    ports:
      - "19092:8080"
  shopping.client:
    image: shoppingclient
    hostname: shoppingclient
    build:
      context: .
      dockerfile: Shopping/Client/Dockerfile
    ports:
      - "19091:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API=http://localhost:19092