//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Client.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopping.Client.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected And Close.
        /// </summary>
        public static string AddSelectedAndClose {
            get {
                return ResourceManager.GetString("AddSelectedAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is invalid..
        /// </summary>
        public static string Amount_is_invalid_ {
            get {
                return ResourceManager.GetString("Amount is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required..
        /// </summary>
        public static string Amount_is_required_ {
            get {
                return ResourceManager.GetString("Amount is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill for {1} month of {0} year.
        /// </summary>
        public static string BillTitleFormat {
            get {
                return ResourceManager.GetString("BillTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car costs.
        /// </summary>
        public static string CarCosts {
            get {
                return ResourceManager.GetString("CarCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost change.
        /// </summary>
        public static string Cost_change {
            get {
                return ResourceManager.GetString("Cost change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bill.
        /// </summary>
        public static string CreateBill {
            get {
                return ResourceManager.GetString("CreateBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        public static string Current_Month {
            get {
                return ResourceManager.GetString("Current Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year.
        /// </summary>
        public static string Current_Year {
            get {
                return ResourceManager.GetString("Current Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required.
        /// </summary>
        public static string Date_is_required {
            get {
                return ResourceManager.GetString("Date is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol A95.
        /// </summary>
        public static string Description_Car_Cost_Default {
            get {
                return ResourceManager.GetString("Description_Car_Cost_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string Description_is_required_ {
            get {
                return ResourceManager.GetString("Description is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End period date.
        /// </summary>
        public static string End_period_date {
            get {
                return ResourceManager.GetString("End period date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Product Name.
        /// </summary>
        public static string First_Product_Name {
            get {
                return ResourceManager.GetString("First Product Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First ProductKind.
        /// </summary>
        public static string First_ProductKind {
            get {
                return ResourceManager.GetString("First ProductKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in design.
        /// </summary>
        public static string in_design {
            get {
                return ResourceManager.GetString("in design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value can not be less than previous value.
        /// </summary>
        public static string IncorrectQuantity {
            get {
                return ResourceManager.GetString("IncorrectQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate value can not be less than zero.
        /// </summary>
        public static string IncorrectRate {
            get {
                return ResourceManager.GetString("IncorrectRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year can not be greater than current and less than 2020; month should be in range 1 - 12..
        /// </summary>
        public static string IncorrectYearOrMonth {
            get {
                return ResourceManager.GetString("IncorrectYearOrMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind Name.
        /// </summary>
        public static string Kind_Name {
            get {
                return ResourceManager.GetString("Kind Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Cost.
        /// </summary>
        public static string Last_Cost {
            get {
                return ResourceManager.GetString("Last Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as hidden.
        /// </summary>
        public static string Mark_as_hidden {
            get {
                return ResourceManager.GetString("Mark as hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as visible.
        /// </summary>
        public static string Mark_as_visible {
            get {
                return ResourceManager.GetString("Mark as visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge products.
        /// </summary>
        public static string Merge_products {
            get {
                return ResourceManager.GetString("Merge products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New bill data.
        /// </summary>
        public static string NewBillData {
            get {
                return ResourceManager.GetString("NewBillData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlay.
        /// </summary>
        public static string Outlay {
            get {
                return ResourceManager.GetString("Outlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the product to add them to receipt.
        /// </summary>
        public static string Please_select_the_product_to_add_them_to_receipt {
            get {
                return ResourceManager.GetString("Please select the product to add them to receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Cost.
        /// </summary>
        public static string Previous_Cost {
            get {
                return ResourceManager.GetString("Previous Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string Previous_Month {
            get {
                return ResourceManager.GetString("Previous Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year.
        /// </summary>
        public static string Previous_Year {
            get {
                return ResourceManager.GetString("Previous Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Value.
        /// </summary>
        public static string PreviousValue {
            get {
                return ResourceManager.GetString("PreviousValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is invalid..
        /// </summary>
        public static string Price_is_invalid_ {
            get {
                return ResourceManager.GetString("Price is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required..
        /// </summary>
        public static string Price_is_required_ {
            get {
                return ResourceManager.GetString("Price is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Kinds.
        /// </summary>
        public static string Product_Kinds {
            get {
                return ResourceManager.GetString("Product Kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        public static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string Saved_successfully {
            get {
                return ResourceManager.GetString("Saved successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Product Kind.
        /// </summary>
        public static string Second_Product_Kind {
            get {
                return ResourceManager.GetString("Second Product Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Product Name.
        /// </summary>
        public static string Second_Product_Name {
            get {
                return ResourceManager.GetString("Second Product Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select products.
        /// </summary>
        public static string Select_products {
            get {
                return ResourceManager.GetString("Select products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Name.
        /// </summary>
        public static string Shop_Name {
            get {
                return ResourceManager.GetString("Shop Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops.
        /// </summary>
        public static string Shops {
            get {
                return ResourceManager.GetString("Shops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden.
        /// </summary>
        public static string Show_hidden {
            get {
                return ResourceManager.GetString("Show hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent On.
        /// </summary>
        public static string Spent_On {
            get {
                return ResourceManager.GetString("Spent On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start period date.
        /// </summary>
        public static string Start_period_date {
            get {
                return ResourceManager.GetString("Start period date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To merge products please select second product.
        /// </summary>
        public static string To_merge_products_please_select_second_product {
            get {
                return ResourceManager.GetString("To merge products please select second product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome in .
        /// </summary>
        public static string Welcome_in {
            get {
                return ResourceManager.GetString("Welcome in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
