// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Shopping.SpecFlow.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PricesFeature : object, Xunit.IClassFixture<PricesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Prices.feature"
#line hidden
        
        public PricesFeature(PricesFeature.FixtureData fixtureData, Shopping_SpecFlow_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Prices", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Kind name",
                        "Product Name"});
            table1.AddRow(new string[] {
                        "Vegetables",
                        "Carrot"});
            table1.AddRow(new string[] {
                        "Vegetables",
                        "Onion"});
#line 6
 testRunner.Given("The Db has the following products", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table2.AddRow(new string[] {
                        "Carrot",
                        "8",
                        "3",
                        "24"});
            table2.AddRow(new string[] {
                        "Onion",
                        "4",
                        "3",
                        "24"});
#line 10
 testRunner.And("The Db has receipt for \'Local\' shop on 1st of the previous month with the followi" +
                    "ng items", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table3.AddRow(new string[] {
                        "Carrot",
                        "10",
                        "3",
                        "30"});
            table3.AddRow(new string[] {
                        "Onion",
                        "5.5",
                        "10",
                        "55"});
#line 14
 testRunner.And("The Db has receipt for \'Local\' shop on 1st of this month with the following items" +
                    "", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table4.AddRow(new string[] {
                        "Carrot",
                        "5",
                        "3",
                        "15"});
            table4.AddRow(new string[] {
                        "Onion",
                        "5",
                        "1",
                        "5"});
#line 18
 testRunner.And("The Db has receipt for \'Gypper market\' shop on 1st of this month with the followi" +
                    "ng items", ((string)(null)), table4, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get prices for products by from last receipt of the shop")]
        [Xunit.TraitAttribute("FeatureTitle", "Prices")]
        [Xunit.TraitAttribute("Description", "Get prices for products by from last receipt of the shop")]
        public void GetPricesForProductsByFromLastReceiptOfTheShop()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get prices for products by from last receipt of the shop", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 24
 testRunner.Given("I have created a new receipt for \'Local\' shop", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product Name"});
                table5.AddRow(new string[] {
                            "Carrot"});
                table5.AddRow(new string[] {
                            "Onion"});
#line 25
 testRunner.And("I have selected the following products", ((string)(null)), table5, "And ");
#line hidden
#line 29
 testRunner.And("I want to get prices for the products of the shop to fill them for selected produ" +
                        "cts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "receiptId",
                            "productIds"});
                table6.AddRow(new string[] {
                            "{TheReceiptId}",
                            "{ProductIds}"});
#line 30
 testRunner.When("I make a GET request to \'api/prices/latest\' with query parameters", ((string)(null)), table6, "When ");
#line hidden
#line 33
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product name",
                            "Prices"});
                table7.AddRow(new string[] {
                            "Carrot",
                            "10"});
                table7.AddRow(new string[] {
                            "Onion",
                            "5.5"});
#line 34
 testRunner.And("The response should contains the following prices", ((string)(null)), table7, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PricesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PricesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
