// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Shopping.SpecFlow.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Statistic_V2Feature : object, global::Xunit.IClassFixture<Statistic_V2Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Statistic.V2", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Statistic.V2.feature"
#line hidden
        
        public Statistic_V2Feature(Statistic_V2Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
            global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                        "Kind name",
                        "Product Name"});
            table26.AddRow(new string[] {
                        "Vegetables",
                        "Carrot"});
            table26.AddRow(new string[] {
                        "Vegetables",
                        "Onion"});
            table26.AddRow(new string[] {
                        "Fruit",
                        "Cherry"});
            table26.AddRow(new string[] {
                        "Fruit",
                        "Lemon"});
#line 6
 await testRunner.GivenAsync("The Db has the following products", ((string)(null)), table26, "Given ");
#line hidden
            global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table27.AddRow(new string[] {
                        "Carrot",
                        "8",
                        "3",
                        "24"});
#line 12
 await testRunner.AndAsync("The Db has receipt for \'Local\' shop on 1st of the previous month with the followi" +
                    "ng items", ((string)(null)), table27, "And ");
#line hidden
            global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table28.AddRow(new string[] {
                        "Carrot",
                        "10",
                        "3",
                        "30"});
            table28.AddRow(new string[] {
                        "Onion",
                        "5.5",
                        "10",
                        "55"});
            table28.AddRow(new string[] {
                        "Cherry",
                        "10",
                        "0.5",
                        "5"});
            table28.AddRow(new string[] {
                        "Lemon",
                        "100",
                        "0.2",
                        "20"});
#line 15
 await testRunner.AndAsync("The Db has receipt for \'Local\' shop on 1st of this month with the following items" +
                    "", ((string)(null)), table28, "And ");
#line hidden
            global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table29.AddRow(new string[] {
                        "Carrot",
                        "5",
                        "3",
                        "15"});
            table29.AddRow(new string[] {
                        "Onion",
                        "5",
                        "1",
                        "5"});
            table29.AddRow(new string[] {
                        "Cherry",
                        "20",
                        "0.5",
                        "10"});
            table29.AddRow(new string[] {
                        "Lemon",
                        "150",
                        "0.2",
                        "30"});
#line 21
 await testRunner.AndAsync("The Db has receipt for \'Gypper market\' shop on 1st of this month with the followi" +
                    "ng items", ((string)(null)), table29, "And ");
#line hidden
            global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                        "Product Name",
                        "Kind Name",
                        "Shop",
                        "PreviousCost",
                        "LastCost",
                        "ChangePercent"});
            table30.AddRow(new string[] {
                        "Carrot",
                        "Vegetables",
                        "Local",
                        "8",
                        "10",
                        "0.25"});
#line 27
 await testRunner.AndAsync("The DB has the price change projection with the following items", ((string)(null)), table30, "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Statistic.V2.feature.ndjson", 9);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get expenses by kind for current month")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [global::Xunit.TraitAttribute("Description", "Get expenses by kind for current month")]
        public async global::System.Threading.Tasks.Task GetExpensesByKindForCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get expenses by kind for current month", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 32
 await testRunner.WhenAsync("I make a GET request to \'api/statistic/expenses-by-kind/current/month\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("The response status should be success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "Kind name",
                            "Expenses"});
                table31.AddRow(new string[] {
                            "Vegetables",
                            "105"});
                table31.AddRow(new string[] {
                            "Fruit",
                            "65"});
#line 34
 await testRunner.AndAsync("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table31, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get expenses by month for year")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [global::Xunit.TraitAttribute("Description", "Get expenses by month for year")]
        public async global::System.Threading.Tasks.Task GetExpensesByMonthForYear()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get expenses by month for year", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 40
 await testRunner.WhenAsync("I make a GET request to \'api/statistic/expenses-by-month/current/year\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
 await testRunner.ThenAsync("The response status should be success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "Month",
                            "Expenses"});
                table32.AddRow(new string[] {
                            "previous month number",
                            "24"});
                table32.AddRow(new string[] {
                            "current month number",
                            "170"});
#line 42
 await testRunner.AndAsync("The response should be Dictionary<int,decimal> with the following data", ((string)(null)), table32, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get expenses by shop for current month")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [global::Xunit.TraitAttribute("Description", "Get expenses by shop for current month")]
        public async global::System.Threading.Tasks.Task GetExpensesByShopForCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get expenses by shop for current month", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 48
 await testRunner.WhenAsync("I make a GET request to \'api/statistic/expenses-by-shop/current/month\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
 await testRunner.ThenAsync("The response status should be success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "Shop",
                            "Expenses"});
                table33.AddRow(new string[] {
                            "Local",
                            "110"});
                table33.AddRow(new string[] {
                            "Gypper market",
                            "60"});
#line 50
 await testRunner.AndAsync("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table33, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get product cost change")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [global::Xunit.TraitAttribute("Description", "Get product cost change")]
        public async global::System.Threading.Tasks.Task GetProductCostChange()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get product cost change", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "page",
                            "pageSize",
                            "orderBy"});
                table34.AddRow(new string[] {
                            "1",
                            "10",
                            "percent"});
#line 56
 await testRunner.WhenAsync("I make a GET request to \'api/statistic/product-cost-change\' with query parameters" +
                        "", ((string)(null)), table34, "When ");
#line hidden
#line 59
 await testRunner.ThenAsync("The response status should be success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "Product Name",
                            "Kind Name",
                            "Shop",
                            "PreviousCost",
                            "LastCost",
                            "ChangePercent"});
                table35.AddRow(new string[] {
                            "Carrot",
                            "Vegetables",
                            "Local",
                            "8",
                            "10",
                            "0.25"});
#line 60
 await testRunner.AndAsync("The response should be collection of ProductCostChange with the following data", ((string)(null)), table35, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get expenses by product kind for current month")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [global::Xunit.TraitAttribute("Description", "Get expenses by product kind for current month")]
        public async global::System.Threading.Tasks.Task GetExpensesByProductKindForCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get expenses by product kind for current month", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 64
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "start",
                            "end"});
                table36.AddRow(new string[] {
                            "{StartOfCurrentMonth}",
                            "{EndOfCurrentMonth}"});
#line 65
 await testRunner.WhenAsync("I make a GET request to \'api/statistic/expenses-by-kinds\' with query parameters", ((string)(null)), table36, "When ");
#line hidden
#line 68
 await testRunner.ThenAsync("The response status should be success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "Kind name",
                            "Expenses"});
                table37.AddRow(new string[] {
                            "Vegetables",
                            "105"});
                table37.AddRow(new string[] {
                            "Fruit",
                            "65"});
#line 69
 await testRunner.AndAsync("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table37, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get expenses by product for the kind of the current month")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [global::Xunit.TraitAttribute("Description", "Get expenses by product for the kind of the current month")]
        public async global::System.Threading.Tasks.Task GetExpensesByProductForTheKindOfTheCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get expenses by product for the kind of the current month", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "kind",
                            "start",
                            "end"});
                table38.AddRow(new string[] {
                            "Fruit",
                            "{StartOfCurrentMonth}",
                            "{EndOfCurrentMonth}"});
#line 75
 await testRunner.WhenAsync("I make a GET request to \'api/statistic/expenses-by-products\' with query parameter" +
                        "s", ((string)(null)), table38, "When ");
#line hidden
#line 78
 await testRunner.ThenAsync("The response status should be success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "Product name",
                            "Expenses"});
                table39.AddRow(new string[] {
                            "Cherry",
                            "15"});
                table39.AddRow(new string[] {
                            "Lemon",
                            "50"});
#line 79
 await testRunner.AndAsync("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table39, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get expenses details for product of the current month")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [global::Xunit.TraitAttribute("Description", "Get expenses details for product of the current month")]
        public async global::System.Threading.Tasks.Task GetExpensesDetailsForProductOfTheCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get expenses details for product of the current month", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "productName",
                            "start",
                            "end"});
                table40.AddRow(new string[] {
                            "Lemon",
                            "{StartOfCurrentMonth}",
                            "{EndOfCurrentMonth}"});
#line 85
 await testRunner.WhenAsync("I make a GET request to \'api/statistic/product-expenses-details\' with query param" +
                        "eters", ((string)(null)), table40, "When ");
#line hidden
#line 88
 await testRunner.ThenAsync("The response status should be success", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "ShopName",
                            "SpentOn",
                            "Price",
                            "Amount"});
                table41.AddRow(new string[] {
                            "Local",
                            "1st of this month",
                            "100",
                            "0.2"});
                table41.AddRow(new string[] {
                            "Gypper market",
                            "1st of this month",
                            "150",
                            "0.2"});
#line 89
 await testRunner.AndAsync("The response should collection of ProductExpensesDetail with the following data", ((string)(null)), table41, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Statistic_V2Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Statistic_V2Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
