// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Shopping.SpecFlow.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Statistic_V2Feature : object, Xunit.IClassFixture<Statistic_V2Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Statistic.V2.feature"
#line hidden
        
        public Statistic_V2Feature(Statistic_V2Feature.FixtureData fixtureData, Shopping_SpecFlow_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Statistic.V2", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Kind name",
                        "Product Name"});
            table20.AddRow(new string[] {
                        "Vegetables",
                        "Carrot"});
            table20.AddRow(new string[] {
                        "Vegetables",
                        "Onion"});
            table20.AddRow(new string[] {
                        "Fruit",
                        "Cherry"});
            table20.AddRow(new string[] {
                        "Fruit",
                        "Lemon"});
#line 6
 testRunner.Given("The Db has the following products", ((string)(null)), table20, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table21.AddRow(new string[] {
                        "Carrot",
                        "8",
                        "3",
                        "24"});
#line 12
 testRunner.And("The Db has receipt for \'Local\' shop on 1st of the previous month with the followi" +
                    "ng items", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table22.AddRow(new string[] {
                        "Carrot",
                        "10",
                        "3",
                        "30"});
            table22.AddRow(new string[] {
                        "Onion",
                        "5.5",
                        "10",
                        "55"});
            table22.AddRow(new string[] {
                        "Cherry",
                        "10",
                        "0.5",
                        "5"});
            table22.AddRow(new string[] {
                        "Lemon",
                        "100",
                        "0.2",
                        "20"});
#line 15
 testRunner.And("The Db has receipt for \'Local\' shop on 1st of this month with the following items" +
                    "", ((string)(null)), table22, "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product Name",
                        "Price",
                        "Amount",
                        "Cost"});
            table23.AddRow(new string[] {
                        "Carrot",
                        "5",
                        "3",
                        "15"});
            table23.AddRow(new string[] {
                        "Onion",
                        "5",
                        "1",
                        "5"});
            table23.AddRow(new string[] {
                        "Cherry",
                        "20",
                        "0.5",
                        "10"});
            table23.AddRow(new string[] {
                        "Lemon",
                        "150",
                        "0.2",
                        "30"});
#line 21
 testRunner.And("The Db has receipt for \'Gypper market\' shop on 1st of this month with the followi" +
                    "ng items", ((string)(null)), table23, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get expenses by kind for current month")]
        [Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [Xunit.TraitAttribute("Description", "Get expenses by kind for current month")]
        public void GetExpensesByKindForCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get expenses by kind for current month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 29
 testRunner.When("I make a GET request to \'api/statistic/expenses-by-kind/current/month\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Kind name",
                            "Expenses"});
                table24.AddRow(new string[] {
                            "Vegetables",
                            "105"});
                table24.AddRow(new string[] {
                            "Fruit",
                            "65"});
#line 31
 testRunner.And("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table24, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get expenses by month for year")]
        [Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [Xunit.TraitAttribute("Description", "Get expenses by month for year")]
        public void GetExpensesByMonthForYear()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get expenses by month for year", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 37
 testRunner.When("I make a GET request to \'api/statistic/expenses-by-month/current/year\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "Month",
                            "Expenses"});
                table25.AddRow(new string[] {
                            "previous month number",
                            "24"});
                table25.AddRow(new string[] {
                            "current month number",
                            "170"});
#line 39
 testRunner.And("The response should be Dictionary<int,decimal> with the following data", ((string)(null)), table25, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get expenses by shop for current month")]
        [Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [Xunit.TraitAttribute("Description", "Get expenses by shop for current month")]
        public void GetExpensesByShopForCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get expenses by shop for current month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 45
 testRunner.When("I make a GET request to \'api/statistic/expenses-by-shop/current/month\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Shop",
                            "Expenses"});
                table26.AddRow(new string[] {
                            "Local",
                            "110"});
                table26.AddRow(new string[] {
                            "Gypper market",
                            "60"});
#line 47
 testRunner.And("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table26, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get product cost change")]
        [Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [Xunit.TraitAttribute("Description", "Get product cost change")]
        public void GetProductCostChange()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get product cost change", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "page",
                            "pageSize",
                            "orderBy"});
                table27.AddRow(new string[] {
                            "1",
                            "10",
                            "percent"});
#line 53
 testRunner.When("I make a GET request to \'api/statistic/product-cost-change\' with query parameters" +
                        "", ((string)(null)), table27, "When ");
#line hidden
#line 56
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product Name",
                            "Kind Name",
                            "Shop",
                            "PreviousCost",
                            "LastCost",
                            "ChangePercent"});
                table28.AddRow(new string[] {
                            "Carrot",
                            "Vegetables",
                            "Local",
                            "8",
                            "10",
                            "0.25"});
#line 57
 testRunner.And("The response should be collection of ProductCostChange with the following data", ((string)(null)), table28, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get expenses by product kind for current month")]
        [Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [Xunit.TraitAttribute("Description", "Get expenses by product kind for current month")]
        public void GetExpensesByProductKindForCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get expenses by product kind for current month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "start",
                            "end"});
                table29.AddRow(new string[] {
                            "{StartOfCurrentMonth}",
                            "{EndOfCurrentMonth}"});
#line 62
 testRunner.When("I make a GET request to \'api/statistic/expenses-by-kinds\' with query parameters", ((string)(null)), table29, "When ");
#line hidden
#line 65
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Kind name",
                            "Expenses"});
                table30.AddRow(new string[] {
                            "Vegetables",
                            "105"});
                table30.AddRow(new string[] {
                            "Fruit",
                            "65"});
#line 66
 testRunner.And("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table30, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get expenses by product for the kind of the current month")]
        [Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [Xunit.TraitAttribute("Description", "Get expenses by product for the kind of the current month")]
        public void GetExpensesByProductForTheKindOfTheCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get expenses by product for the kind of the current month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "kind",
                            "start",
                            "end"});
                table31.AddRow(new string[] {
                            "Fruit",
                            "{StartOfCurrentMonth}",
                            "{EndOfCurrentMonth}"});
#line 72
 testRunner.When("I make a GET request to \'api/statistic/expenses-by-products\' with query parameter" +
                        "s", ((string)(null)), table31, "When ");
#line hidden
#line 75
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "Product name",
                            "Expenses"});
                table32.AddRow(new string[] {
                            "Cherry",
                            "15"});
                table32.AddRow(new string[] {
                            "Lemon",
                            "50"});
#line 76
 testRunner.And("The response should be Dictionary<string,decimal> with the following data", ((string)(null)), table32, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get expenses details for product of the current month")]
        [Xunit.TraitAttribute("FeatureTitle", "Statistic.V2")]
        [Xunit.TraitAttribute("Description", "Get expenses details for product of the current month")]
        public void GetExpensesDetailsForProductOfTheCurrentMonth()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get expenses details for product of the current month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 81
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "productName",
                            "start",
                            "end"});
                table33.AddRow(new string[] {
                            "Lemon",
                            "{StartOfCurrentMonth}",
                            "{EndOfCurrentMonth}"});
#line 82
 testRunner.When("I make a GET request to \'api/statistic/product-expenses-details\' with query param" +
                        "eters", ((string)(null)), table33, "When ");
#line hidden
#line 85
 testRunner.Then("The response status should be success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "ShopName",
                            "SpentOn",
                            "Price",
                            "Amount"});
                table34.AddRow(new string[] {
                            "Local",
                            "1st of this month",
                            "100",
                            "0.2"});
                table34.AddRow(new string[] {
                            "Gypper market",
                            "1st of this month",
                            "150",
                            "0.2"});
#line 86
 testRunner.And("The response should collection of ProductExpensesDetail with the following data", ((string)(null)), table34, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                Statistic_V2Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                Statistic_V2Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
